name:                burrows-wheeler
version:             0.1.0.0
github:              "Anteproperispomenon/burrows-wheeler"
license:             MIT
author:              "David Wilson"
# maintainer:          "example@example.com"
copyright:           "2025 David Wilson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Simple BWT functions
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Anteproperispomenon/burrows-wheeler#readme>

default-extensions:
  - ImportQualifiedPost
  - MultiWayIf

dependencies:
- base >= 4.14 && < 5
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

include-dirs:
  - cbwt
  - openbwt

library:
  source-dirs: src
  include-dirs:
   - cbwt
   - openbwt
  c-sources:
   - cbwt/encode.c
   - cbwt/decode.c
   - openbwt/openbwt.c

executables:
  burrows-wheeler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - burrows-wheeler
    - directory

tests:
  burrows-wheeler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - burrows-wheeler
